# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(help_text='Max of 20 letters', max_length=20, null=True)),
                ('platform', models.CharField(help_text='Max of 20 letters', max_length=20, null=True)),
                ('cover_img', models.ImageField(default=False, upload_to='game_covers/')),
                ('genre', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('RPG', 'Role Play Game'), ('RCG', 'Racing')], max_length=20, null=True)),
            ],
        ),
    ]
