# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_steam', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.AddField(
            model_name='usergames',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_steam.Game'),
        ),
        migrations.AddField(
            model_name='usergames',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='owners',
            field=models.ManyToManyField(through='my_steam.UserGames', to=settings.AUTH_USER_MODEL),
        ),
    ]
